### ISSUE TITLE
How to remove the trackers?

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/spftoolbox_ynh#11]
How to remove these?

```
ajax.googleapis.com
bootstrapcdn.com
maxcdn.bootstrapcdn.com
googletagmanager.com
www.googletagmanager.com
```

The developer says he uses them for certain reasons but the service works without - https://github.com/charlesabarnes/SPFtoolbox/issues/52

But for yunohost can't these be removed=

**Comment by ericgaspar** [comment]
Upstream seems to have removed the trackers
